components:
    schemas:
        Site:
            # @review
            description:
                Represents the site being created.
            properties:
                externalReferenceCode:
                    description:
                        The site's external reference code.
                    type: string
                friendlyUrlPath:
                    readOnly: true
                    type: string
                id:
                    format: int64
                    readOnly: true
                    type: integer
                key:
                    readOnly: true
                    type: string
                membershipType:
                    description:
                        The default value is open.
                    enum:
                        - open
                        - private
                        - restricted
                    type: string
                    writeOnly: true
                name:
                    type: string
                parentSiteKey:
                    type: string
                    writeOnly: true
                templateKey:
                    type: string
                    writeOnly: true
                templateType:
                    enum:
                        - site-initializer
                        - site-template
                    type: string
                    writeOnly: true
            required:
                - name
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.headless.site.client', and version '1.0.19'."
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    title: Liferay Sites Headless API
    version: v1.0
openapi: 3.0.1
paths:
    "/sites/{siteId}":
        delete:
            description:
                # @review
                Deletes a site and all of its associated content.
            operationId: deleteSite
            parameters:
                - in: path
                  name: siteId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["Site"]
    /sites:
        post:
            description:
                Adds a new site
            operationId: postSite
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Site"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Site"
                    multipart/form-data:
                        schema:
                            properties:
                                file:
                                    format: binary
                                    type: string
                                site:
                                    $ref: "#/components/schemas/Site"
                            type: object
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Site"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Site"
                    description:
                        default response
            # @review
            tags: ["Site"]
    /sites/by-external-reference-code/{externalReferenceCode}:
        delete:
            # @review
            description:
                Deletes a site and all of its associated content.
            operationId: deleteSiteByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["Site"]
        get:
            operationId: getSiteByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Site"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Site"
                    description:
                        default response
            tags: ["Site"]
        put:
            description:
                Adds or update a new site
            operationId: putSiteByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            properties:
                                file:
                                    format: binary
                                    type: string
                            type: object
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Site"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Site"
                    description:
                        default response
            tags: ["Site"]
    /sites/by-external-reference-code/{externalReferenceCode}/site-initializer:
        get:
            operationId: getSiteByExternalReferenceCodeSiteInitializer
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/zip:
                            schema:
                                format: binary
                                type: string
            tags: ["Site"]