components:
    schemas:
        Message:
            properties:
                key:
                    type: string
                languageId:
                    type: string
                value:
                    type: string
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.portal.language.rest.client', and version '1.0.4'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Language"
    version: v1.0
openapi: 3.0.1
paths:
    "/messages":
        delete:
            operationId: deleteMessage
            parameters:
                - in: query
                  name: key
                  required: true
                  schema:
                      type: string
                - in: query
                  name: languageId
                  required: false
                  schema:
                      type: string
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["Message"]
        get:
            operationId: getMessage
            parameters:
                - in: query
                  name: key
                  required: true
                  schema:
                      type: string
                - in: query
                  name: languageId
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Message"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Message"
            tags: ["Message"]
        post:
            operationId: postMessage
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Message"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Message"
            responses:
                201:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Message"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Message"
            tags: ["Message"]
        put:
            operationId: putMessage
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Message"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Message"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Message"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Message"
            tags: ["Message"]
    "/messages/import":
        post:
            operationId: postMessageImport
            parameters:
                - in: query
                  name: languageId
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            properties:
                                file:
                                    format: binary
                                    type: string
                            type: object
            responses:
                200:
                    content:
                        application/json: {}
                        application/xml: {}
                400:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["Message"]