apiDir: "../osb-testray-rest-api/src/main/java"
apiPackagePath: "com.liferay.osb.testray.rest"
application:
    baseURI: "/osb-testray-rest"
    className: "OSBTestrayRESTApplication"
    name: "Liferay.OSB.Testray.REST"
author: "José Abelenda"
clientDir: "../osb-testray-rest-client/src/main/java"
compatibilityVersion: 6
forcePredictableOperationId: true
testDir: "../osb-testray-rest-test/src/testIntegration/java"