apiDir: "../headless-admin-site-api/src/main/java"
apiPackagePath: "com.liferay.headless.admin.site"
application:
    baseURI: "/headless-admin-site"
    className: "HeadlessAdminSiteApplication"
    name: "Liferay.Headless.Admin.Site"
author: "Rubén Pulido"
clientDir: "../headless-admin-site-client/src/main/java"
compatibilityVersion: 6
forcePredictableOperationId: false
generateBatch: true
generateGraphQL: true
testDir: "../headless-admin-site-test/src/testIntegration/java"