components:
    schemas:
        AppearsOnHistogram:
            properties:
                canonicalUrl:
                    type: string
                metrics:
                    items:
                        $ref: "#/components/schemas/Metric"
                    type: array
                pageTitle:
                    type: string
                total:
                    format: double
                    type: number
                totalValue:
                    format: double
                    type: number
        AssetAppearsOnHistogram:
            properties:
                appearsOnHistograms:
                    items:
                        $ref: "#/components/schemas/AppearsOnHistogram"
                    type: array
                metricName:
                    type: string
        AssetAppearsOnHistogramMetric:
            properties:
                assetAppearsOnHistograms:
                    items:
                        $ref: "#/components/schemas/AssetAppearsOnHistogram"
                    type: array
        AssetDeviceMetric:
            properties:
                deviceMetrics:
                    items:
                        $ref: "#/components/schemas/DeviceMetric"
                    type: array
        AssetHistogramMetric:
            properties:
                histograms:
                    items:
                        $ref: "#/components/schemas/Histogram"
                    type: array
        AssetMetric:
            properties:
                assetId:
                    type: string
                assetTitle:
                    type: string
                assetType:
                    type: string
                dataSourceId:
                    type: string
                defaultMetric:
                    $ref: "#/components/schemas/Metric"
                selectedMetrics:
                    items:
                        $ref: "#/components/schemas/Metric"
                    type: array
        DeviceMetric:
            properties:
                metricName:
                    type: string
                metrics:
                    items:
                        $ref: "#/components/schemas/Metric"
                    type: array
        Histogram:
            properties:
                metricName:
                    type: string
                metrics:
                    items:
                        $ref: "#/components/schemas/Metric"
                    type: array
                total:
                    format: double
                    type: number
                totalValue:
                    format: double
                    type: number
        Metric:
            properties:
                metricType:
                    type: string
                previousValue:
                    format: double
                    type: number
                previousValueKey:
                    type: string
                trend:
                    $ref: "#/components/schemas/Trend"
                value:
                    format: double
                    type: number
                valueKey:
                    type: string
        Trend:
            properties:
                percentage:
                    format: double
                    type: number
                trendClassification:
                    enum: [NEGATIVE, NEUTRAL, POSITIVE]
                    type: string
info:
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "{groupId}/asset-metrics/{assetType}":
        get:
            operationId: getGroupAssetMetric
            parameters:
                - in: path
                  name: groupId
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: assetType
                  schema:
                      type: string
                - in: query
                  name: assetId
                  schema:
                      type: string
                - in: query
                  name: identityType
                  schema:
                      enum: [ALL, KNOWN, UNKNOWN]
                      type: string
                - in: query
                  name: rangeKey
                  schema:
                      type: integer
                - in: query
                  name: selectedMetrics
                  schema:
                      items:
                          type: string
                      type: array
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AssetMetric"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AssetMetric"
            tags: ["AssetMetric"]
    "{groupId}/asset-metrics/{assetType}/appears-on/histogram":
        get:
            operationId: getGroupAssetMetricAssetTypeAppearsOnHistogram
            parameters:
                - in: path
                  name: groupId
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: assetType
                  schema:
                      type: string
                - in: query
                  name: assetId
                  schema:
                      type: string
                - in: query
                  name: identityType
                  schema:
                      enum: [ALL, KNOWN, UNKNOWN]
                      type: string
                - in: query
                  name: rangeKey
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AssetAppearsOnHistogramMetric"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AssetAppearsOnHistogramMetric"
            tags: ["AssetAppearsOnHistogramMetric"]
    "{groupId}/asset-metrics/{assetType}/devices":
        get:
            operationId: getGroupAssetMetricAssetTypeDevice
            parameters:
                - in: path
                  name: groupId
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: assetType
                  schema:
                      type: string
                - in: query
                  name: assetId
                  schema:
                      type: string
                - in: query
                  name: identityType
                  schema:
                      enum: [ALL, KNOWN, UNKNOWN]
                      type: string
                - in: query
                  name: rangeKey
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AssetDeviceMetric"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AssetDeviceMetric"
            tags: ["AssetDeviceMetric"]
    "{groupId}/asset-metrics/{assetType}/histogram":
        get:
            operationId: getGroupAssetMetricAssetTypeHistogram
            parameters:
                - in: path
                  name: groupId
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: assetType
                  schema:
                      type: string
                - in: query
                  name: assetId
                  schema:
                      type: string
                - in: query
                  name: identityType
                  schema:
                      enum: [ALL, KNOWN, UNKNOWN]
                      type: string
                - in: query
                  name: rangeKey
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AssetHistogramMetric"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AssetHistogramMetric"
            tags: ["AssetHistogramMetric"]