apiDir: "../analytics-dxp-entity-rest-api/src/main/java"
apiPackagePath: "com.liferay.analytics.dxp.entity.rest"
author: "Marcos Martins, Rachael Koestartyo, Riccardo Ferrari"
compatibilityVersion: 6
forcePredictableOperationId: true
liferayEnterpriseApp: true