apiDir: "../captcha-rest-api/src/main/java"
apiPackagePath: "com.liferay.captcha.rest"
application:
    baseURI: "/captcha"
    className: "CaptchaRESTApplication"
    name: "Liferay.Captcha.REST"
author: "Loc Pham"
clientDir: "../captcha-rest-client/src/main/java"
compatibilityVersion: 6
forcePredictableOperationId: true
generateBatch: false
generateGraphQL: false
testDir: "../captcha-rest-test/src/testIntegration/java"