components:
    schemas:
        Captcha:
            properties:
                answer:
                    type: string
                image:
                    type: string
                token:
                    type: string
            required:
                - token
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.captcha.rest.client', and version '1.0.12'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/captcha/challenge":
        get:
            operationId: getCaptchaChallenge
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Captcha"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Captcha"
                    description:
                        Send a captcha token and image.
            tags: ["Captcha"]
    "/captcha/response":
        post:
            operationId: postCaptchaResponse
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Captcha"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Captcha"
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
                400:
                    content:
                        application/json: {}
                        application/xml: {}
                    description:
                        Invalid answer provided
            tags: ["Captcha"]