jobs:
    publish-liferay-stripe-workspace:
        secrets: inherit
        uses: ./.github/workflows/ci-publish-workspace.yaml
        with:
            workspace-name: liferay-stripe-workspace
name: CI Publish liferay-stripe-workspace
on:
    push:
        branches:
            - master
        paths:
            - workspaces/liferay-stripe-workspace/**